# Generated by Django 5.0 on 2023-12-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks_electronics', '0001_initial'),
        ('products', '0001_initial'),
        ('factory', '0002_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoleProprietor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='имя индивидуального предпринимателя')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proprietor_contacts', to='contacts.contact')),
                ('factory_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_supplier_for_proprietor', to='factory.factory', verbose_name='завод-поставщик')),
                ('main_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_proprietor', to='networks_electronics.mainnetwork', verbose_name='основная сеть')),
                ('products', models.ManyToManyField(blank=True, related_name='proprietor_products', to='products.product')),
                ('retail_network_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retail_network_supplier', to='networks_electronics.retailnetwork', verbose_name='поставщик розничная сеть')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
    ]
