# Generated by Django 5.0 on 2023-12-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('products', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_contact', to='contacts.contact')),
                ('products', models.ManyToManyField(blank=True, related_name='main_network_product', to='products.product')),
            ],
            options={
                'verbose_name': 'Основная сеть',
                'verbose_name_plural': 'Основные сети',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название сети')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='debt_to_supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='network_contacts', to='contacts.contact')),
                ('factory_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier', to='factory.factory', verbose_name='поставщик')),
                ('main_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_network_retail_net', to='networks_electronics.mainnetwork', verbose_name='основная сеть')),
                ('products', models.ManyToManyField(blank=True, related_name='network_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
    ]
